// <auto-generated />
using System;
using DataAccessLayer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccessLayer.Migrations
{
    [DbContext(typeof(EVRentalDBContext))]
    [Migration("20251112050608_AddBatteryCapacityToVehicle")]
    partial class AddBatteryCapacityToVehicle
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DataAccessLayer.Entities.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAt");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("UpdatedAt");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Account", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateDate = new DateTime(2025, 10, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "admin@evrental.com",
                            FullName = "Administrator",
                            IsActive = true,
                            PasswordHash = "$2a$12$cCtbISaErU6KdR09HUiVvuX0Ur2saXpU/sEB3sQJ72obhp8jKbCa.",
                            Phone = "0123456789",
                            Role = 2,
                            UpdateDate = new DateTime(2025, 10, 24, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            CreateDate = new DateTime(2025, 10, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "staff@evrental.com",
                            FullName = "Nguyen Van Staff",
                            IsActive = true,
                            PasswordHash = "$2a$12$cCtbISaErU6KdR09HUiVvuX0Ur2saXpU/sEB3sQJ72obhp8jKbCa.",
                            Phone = "0987654321",
                            Role = 1,
                            UpdateDate = new DateTime(2025, 10, 24, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            CreateDate = new DateTime(2025, 10, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "renter1@gmail.com",
                            FullName = "Tran Thi Renter",
                            IsActive = true,
                            PasswordHash = "$2a$12$cCtbISaErU6KdR09HUiVvuX0Ur2saXpU/sEB3sQJ72obhp8jKbCa.",
                            Phone = "0901234567",
                            Role = 0,
                            UpdateDate = new DateTime(2025, 10, 25, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            CreateDate = new DateTime(2025, 10, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "renter2@gmail.com",
                            FullName = "Le Van Renter",
                            IsActive = true,
                            PasswordHash = "$2a$12$cCtbISaErU6KdR09HUiVvuX0Ur2saXpU/sEB3sQJ72obhp8jKbCa.",
                            Phone = "0912345678",
                            Role = 0,
                            UpdateDate = new DateTime(2025, 10, 25, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("DataAccessLayer.Entities.InspectionProblem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Evidence")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IncidentType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<decimal>("PenaltyAmount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(12,2)")
                        .HasDefaultValue(0m);

                    b.Property<int>("RentalId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("RentalId");

                    b.ToTable("InspectionProblems");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(12,2)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("RentalId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValue("pending");

                    b.Property<string>("TransactionRef")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("RentalId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.RatingReview", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<int>("RentalId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("RentalId")
                        .IsUnique();

                    b.ToTable("RatingReviews");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.RentalRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ActualEndTime")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("BasePrice")
                        .HasColumnType("decimal(12,2)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("DepositFee")
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("Discount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(12,2)")
                        .HasDefaultValue(0m);

                    b.Property<DateTime?>("ExpectedEndTime")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("ExtraFees")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(12,2)")
                        .HasDefaultValue(0m);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("OtpCode")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<int>("PickupStationId")
                        .HasColumnType("int");

                    b.Property<int>("RenterId")
                        .HasColumnType("int");

                    b.Property<decimal>("ReservationFee")
                        .HasColumnType("decimal(12,2)");

                    b.Property<int?>("ReturnStationId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(12,2)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("VehicleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PickupStationId");

                    b.HasIndex("RenterId");

                    b.HasIndex("ReturnStationId");

                    b.HasIndex("VehicleId");

                    b.ToTable("RentalRecords");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.Station", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Stations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "123 Lê Lợi, Phường Bến Thành, Quận 1, TP.HCM",
                            CreateDate = new DateTime(2025, 10, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Name = "Trạm Quận 1 - Bến Thành",
                            State = "Active",
                            UpdateDate = new DateTime(2025, 10, 20, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            Address = "456 Cộng Hòa, Phường 13, Quận Tân Bình, TP.HCM",
                            CreateDate = new DateTime(2025, 10, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Name = "Trạm Quận 3 - Cộng Hòa",
                            State = "Active",
                            UpdateDate = new DateTime(2025, 10, 20, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            Address = "789 Nguyễn Văn Linh, Phường Tân Phú, Quận 7, TP.HCM",
                            CreateDate = new DateTime(2025, 10, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Name = "Trạm Quận 7 - Phú Mỹ Hưng",
                            State = "Active",
                            UpdateDate = new DateTime(2025, 10, 20, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            Address = "208 Nguyễn Hữu Cảnh, Phường 22, TP. Thủ Đức, TP.HCM",
                            CreateDate = new DateTime(2025, 10, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Name = "Trạm Thủ Đức - Landmark 81",
                            State = "Active",
                            UpdateDate = new DateTime(2025, 10, 20, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("DataAccessLayer.Entities.Vehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BatteryCapacity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(6,2)")
                        .HasDefaultValue(0m);

                    b.Property<string>("Brand")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Features")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("MaxDistance")
                        .HasColumnType("int");

                    b.Property<string>("Model")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PlateNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("PricePerDay")
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("PricePerHour")
                        .HasColumnType("decimal(12,2)");

                    b.Property<int>("StationId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("VehicleType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("seartCapacity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StationId");

                    b.ToTable("Vehicles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BatteryCapacity = 37.5m,
                            Brand = "VinFast",
                            CreateDate = new DateTime(2025, 10, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Features = "{\"gps\":true,\"insurance\":true,\"bluetooth\":true,\"airConditioner\":true}",
                            ImageUrl = "https://www.vinfastvietnam.net.vn/uploads/data/3097/imgproducts/vinfastvietnam.net.vnvfe34.jpg3.jpg",
                            IsDeleted = false,
                            MaxDistance = 285,
                            Model = "VF e34",
                            Name = "VinFast VF e34",
                            PlateNumber = "59A-12345",
                            PricePerDay = 1200000m,
                            PricePerHour = 150000m,
                            StationId = 1,
                            Status = 0,
                            UpdateDate = new DateTime(2025, 10, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VehicleType = "car",
                            seartCapacity = 5
                        },
                        new
                        {
                            Id = 3,
                            BatteryCapacity = 82m,
                            Brand = "Tesla",
                            CreateDate = new DateTime(2025, 10, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Features = "{\"gps\":true,\"insurance\":true,\"bluetooth\":true,\"airConditioner\":true,\"autopilot\":true}",
                            ImageUrl = "https://giaxeoto.vn/admin/upload/images/resize/640-tesla-model-3-2024-co-gi-moi.jpg",
                            IsDeleted = false,
                            MaxDistance = 491,
                            Model = "Model 3 Standard Range",
                            Name = "Tesla Model 3",
                            PlateNumber = "59C-33333",
                            PricePerDay = 1800000m,
                            PricePerHour = 220000m,
                            StationId = 2,
                            Status = 0,
                            UpdateDate = new DateTime(2025, 10, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VehicleType = "car",
                            seartCapacity = 5
                        },
                        new
                        {
                            Id = 5,
                            BatteryCapacity = 84m,
                            Brand = "BMW",
                            CreateDate = new DateTime(2025, 10, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Features = "{\"gps\":true,\"insurance\":true,\"bluetooth\":true,\"airConditioner\":true,\"sunroof\":true,\"leatherSeats\":true,\"panoramicRoof\":true}",
                            ImageUrl = "https://images.netdirector.co.uk/gforces-auto/image/upload/w_412,h_309,q_auto,c_fill,f_auto,fl_lossy/auto-titan/e9fc28a92a2bff98fdb38daeb05779d0/ix3_new_highlights.png",
                            IsDeleted = false,
                            MaxDistance = 460,
                            Model = "iX3 M Sport",
                            Name = "BMW iX3",
                            PlateNumber = "51C-55555",
                            PricePerDay = 2200000m,
                            PricePerHour = 280000m,
                            StationId = 3,
                            Status = 0,
                            UpdateDate = new DateTime(2025, 10, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VehicleType = "car",
                            seartCapacity = 5
                        },
                        new
                        {
                            Id = 7,
                            BatteryCapacity = 93m,
                            Brand = "Audi",
                            CreateDate = new DateTime(2025, 10, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Features = "{\"gps\":true,\"insurance\":true,\"bluetooth\":true,\"airConditioner\":true,\"leatherSeats\":true,\"sportMode\":true}",
                            ImageUrl = "https://i1-vnexpress.vnecdn.net/2024/11/23/DSC09878JPG-1732351567.jpg?w=750&h=450&q=100&dpr=1&fit=crop&s=UVB1kqgA08fA_pGNG7EjvA",
                            IsDeleted = false,
                            MaxDistance = 488,
                            Model = "e-tron GT quattro",
                            Name = "Audi e-tron GT",
                            PlateNumber = "51E-99999",
                            PricePerDay = 2500000m,
                            PricePerHour = 320000m,
                            StationId = 4,
                            Status = 0,
                            UpdateDate = new DateTime(2025, 10, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VehicleType = "car",
                            seartCapacity = 4
                        },
                        new
                        {
                            Id = 9,
                            BatteryCapacity = 75m,
                            Brand = "VinFast",
                            CreateDate = new DateTime(2025, 10, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Features = "{\"gps\":true,\"insurance\":true,\"bluetooth\":true,\"airConditioner\":true,\"autopilot\":true}",
                            ImageUrl = "https://vinfast-cars.vn/wp-content/uploads/2025/02/vinfast-vf8-den.png",
                            IsDeleted = false,
                            MaxDistance = 420,
                            Model = "VF 8 Plus",
                            Name = "VinFast VF 8",
                            PlateNumber = "59E-77777",
                            PricePerDay = 1400000m,
                            PricePerHour = 180000m,
                            StationId = 1,
                            Status = 0,
                            UpdateDate = new DateTime(2025, 10, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VehicleType = "car",
                            seartCapacity = 5
                        },
                        new
                        {
                            Id = 11,
                            BatteryCapacity = 107.8m,
                            Brand = "Mercedes-Benz",
                            CreateDate = new DateTime(2025, 10, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Features = "{\"gps\":true,\"insurance\":true,\"bluetooth\":true,\"airConditioner\":true,\"leatherSeats\":true,\"massage\":true,\"panoramicRoof\":true}",
                            ImageUrl = "https://i1-vnexpress.vnecdn.net/2023/03/29/Mercedes-EQS-2022-VnE-7034-JPG.jpg?w=2400&h=0&q=100&dpr=1&fit=crop&s=VNrfMglzD7glUa199o-N6A&t=image",
                            IsDeleted = false,
                            MaxDistance = 770,
                            Model = "EQS 450+",
                            Name = "Mercedes EQS",
                            PlateNumber = "59G-22233",
                            PricePerDay = 2800000m,
                            PricePerHour = 350000m,
                            StationId = 2,
                            Status = 0,
                            UpdateDate = new DateTime(2025, 10, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VehicleType = "car",
                            seartCapacity = 5
                        },
                        new
                        {
                            Id = 13,
                            BatteryCapacity = 93.2m,
                            Brand = "Porsche",
                            CreateDate = new DateTime(2025, 10, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Features = "{\"gps\":true,\"insurance\":true,\"bluetooth\":true,\"airConditioner\":true,\"leatherSeats\":true,\"sportMode\":true,\"launch\":true}",
                            ImageUrl = "https://i1-vnexpress.vnecdn.net/2024/10/18/Porsche-Taycan-Vnexpress-net-11-JPG.jpg?w=2400&h=0&q=100&dpr=1&fit=crop&s=LoskMEDqKHzXgrHyeWd5Ag&t=image",
                            IsDeleted = false,
                            MaxDistance = 484,
                            Model = "Taycan 4S",
                            Name = "Porsche Taycan",
                            PlateNumber = "51G-44455",
                            PricePerDay = 3000000m,
                            PricePerHour = 380000m,
                            StationId = 3,
                            Status = 0,
                            UpdateDate = new DateTime(2025, 10, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VehicleType = "car",
                            seartCapacity = 4
                        },
                        new
                        {
                            Id = 15,
                            BatteryCapacity = 92m,
                            Brand = "VinFast",
                            CreateDate = new DateTime(2025, 10, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Features = "{\"gps\":true,\"insurance\":true,\"bluetooth\":true,\"airConditioner\":true,\"7seats\":true,\"panoramicRoof\":true}",
                            ImageUrl = "https://shop.vinfastauto.com/on/demandware.static/-/Sites-app_vinfast_vn-Library/default/dw1a73c862/images/PDP/vf9/202406/exterior/CE1W.webp",
                            IsDeleted = false,
                            MaxDistance = 438,
                            Model = "VF 9 Plus",
                            Name = "VinFast VF 9",
                            PlateNumber = "59I-66677",
                            PricePerDay = 1600000m,
                            PricePerHour = 200000m,
                            StationId = 4,
                            Status = 0,
                            UpdateDate = new DateTime(2025, 10, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VehicleType = "car",
                            seartCapacity = 7
                        },
                        new
                        {
                            Id = 17,
                            BatteryCapacity = 82m,
                            Brand = "Tesla",
                            CreateDate = new DateTime(2025, 10, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Features = "{\"gps\":true,\"insurance\":true,\"bluetooth\":true,\"airConditioner\":true,\"autopilot\":true,\"7seats\":true}",
                            ImageUrl = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSQuPPGwtfobtphn2JnZfRLJU_ELJXj4mEweQ&s",
                            IsDeleted = false,
                            MaxDistance = 525,
                            Model = "Model Y Long Range",
                            Name = "Tesla Model Y",
                            PlateNumber = "51I-77788",
                            PricePerDay = 1900000m,
                            PricePerHour = 240000m,
                            StationId = 1,
                            Status = 0,
                            UpdateDate = new DateTime(2025, 10, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VehicleType = "car",
                            seartCapacity = 7
                        },
                        new
                        {
                            Id = 19,
                            BatteryCapacity = 84m,
                            Brand = "Hyundai",
                            CreateDate = new DateTime(2025, 10, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Features = "{\"gps\":true,\"insurance\":true,\"bluetooth\":true,\"airConditioner\":true,\"solarRoof\":true}",
                            ImageUrl = "https://i1-vnexpress.vnecdn.net/2023/07/31/Hyundai-IONIQ-5-7.jpg?w=2400&h=0&q=100&dpr=1&fit=crop&s=gqOfVmNy6EZxHps0rNBfCA&t=image",
                            IsDeleted = false,
                            MaxDistance = 481,
                            Model = "Ioniq 5 Long Range",
                            Name = "Hyundai Ioniq 5",
                            PlateNumber = "59J-88899",
                            PricePerDay = 1500000m,
                            PricePerHour = 190000m,
                            StationId = 2,
                            Status = 0,
                            UpdateDate = new DateTime(2025, 10, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VehicleType = "car",
                            seartCapacity = 5
                        },
                        new
                        {
                            Id = 21,
                            BatteryCapacity = 84m,
                            Brand = "Kia",
                            CreateDate = new DateTime(2025, 10, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Features = "{\"gps\":true,\"insurance\":true,\"bluetooth\":true,\"airConditioner\":true,\"fastCharging\":true}",
                            ImageUrl = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTDRNkoUruCHw69jdLnwmvz09ncLCsAcLnsJA&s",
                            IsDeleted = false,
                            MaxDistance = 528,
                            Model = "EV6 GT-Line",
                            Name = "Kia EV6",
                            PlateNumber = "51J-99900",
                            PricePerDay = 1550000m,
                            PricePerHour = 195000m,
                            StationId = 3,
                            Status = 0,
                            UpdateDate = new DateTime(2025, 10, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VehicleType = "car",
                            seartCapacity = 5
                        },
                        new
                        {
                            Id = 23,
                            BatteryCapacity = 100m,
                            Brand = "Polestar",
                            CreateDate = new DateTime(2025, 10, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Features = "{\"gps\":true,\"insurance\":true,\"bluetooth\":true,\"airConditioner\":true,\"googleIntegration\":true}",
                            ImageUrl = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTFP_xRoDnlB2qUUnef4lw1c-HTf7Xnvi_hWw&s",
                            IsDeleted = false,
                            MaxDistance = 540,
                            Model = "Polestar 2 Long Range",
                            Name = "Polestar 2",
                            PlateNumber = "59L-33322",
                            PricePerDay = 1850000m,
                            PricePerHour = 230000m,
                            StationId = 4,
                            Status = 0,
                            UpdateDate = new DateTime(2025, 10, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VehicleType = "car",
                            seartCapacity = 5
                        },
                        new
                        {
                            Id = 25,
                            BatteryCapacity = 60.48m,
                            Brand = "BYD",
                            CreateDate = new DateTime(2025, 10, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Features = "{\"gps\":true,\"insurance\":true,\"bluetooth\":true,\"airConditioner\":true,\"panoramicSunroof\":true}",
                            ImageUrl = "https://img1.oto.com.vn/2024/07/26/OpzfnMD2/atto-3-0f7e.webp",
                            IsDeleted = false,
                            MaxDistance = 480,
                            Model = "Atto 3 Extended",
                            Name = "BYD Atto 3",
                            PlateNumber = "51M-66655",
                            PricePerDay = 1450000m,
                            PricePerHour = 185000m,
                            StationId = 1,
                            Status = 0,
                            UpdateDate = new DateTime(2025, 10, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VehicleType = "car",
                            seartCapacity = 5
                        },
                        new
                        {
                            Id = 27,
                            BatteryCapacity = 87m,
                            Brand = "Nissan",
                            CreateDate = new DateTime(2025, 10, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Features = "{\"gps\":true,\"insurance\":true,\"bluetooth\":true,\"airConditioner\":true,\"proPilot\":true}",
                            ImageUrl = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTNR4feHONvrN5Y-HK13689YKvLgkYgtqWiyA&s",
                            IsDeleted = false,
                            MaxDistance = 500,
                            Model = "Ariya e-4ORCE",
                            Name = "Nissan Ariya",
                            PlateNumber = "51L-44433",
                            PricePerDay = 1700000m,
                            PricePerHour = 210000m,
                            StationId = 2,
                            Status = 0,
                            UpdateDate = new DateTime(2025, 10, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VehicleType = "car",
                            seartCapacity = 5
                        },
                        new
                        {
                            Id = 28,
                            BatteryCapacity = 112m,
                            Brand = "Lexus",
                            CreateDate = new DateTime(2025, 10, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Features = "{\"gps\":true,\"insurance\":true,\"bluetooth\":true,\"airConditioner\":true,\"leatherSeats\":true,\"markLevinson\":true}",
                            ImageUrl = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT8Xr-6nI1VqKU3Jn7pKYqIw-8L_xK3y8T9cxo&s",
                            IsDeleted = false,
                            MaxDistance = 565,
                            Model = "ES 300h Hybrid",
                            Name = "Lexus ES 300h",
                            PlateNumber = "59N-11234",
                            PricePerDay = 2000000m,
                            PricePerHour = 250000m,
                            StationId = 3,
                            Status = 0,
                            UpdateDate = new DateTime(2025, 10, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VehicleType = "car",
                            seartCapacity = 5
                        },
                        new
                        {
                            Id = 29,
                            BatteryCapacity = 78m,
                            Brand = "Volvo",
                            CreateDate = new DateTime(2025, 10, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Features = "{\"gps\":true,\"insurance\":true,\"bluetooth\":true,\"airConditioner\":true,\"panoramicSunroof\":true,\"safetyFeatures\":true}",
                            ImageUrl = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQqJME5P0q8Z9p5Y5e5o5o5o5o5o5o5o5o&s",
                            IsDeleted = false,
                            MaxDistance = 470,
                            Model = "XC60 Recharge",
                            Name = "Volvo XC60",
                            PlateNumber = "51N-22345",
                            PricePerDay = 1900000m,
                            PricePerHour = 240000m,
                            StationId = 4,
                            Status = 0,
                            UpdateDate = new DateTime(2025, 10, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VehicleType = "car",
                            seartCapacity = 5
                        },
                        new
                        {
                            Id = 30,
                            BatteryCapacity = 100m,
                            Brand = "Jaguar",
                            CreateDate = new DateTime(2025, 10, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Features = "{\"gps\":true,\"insurance\":true,\"bluetooth\":true,\"airConditioner\":true,\"leatherSeats\":true,\"premiumAudio\":true,\"fastCharging\":true}",
                            ImageUrl = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS3_3_3_3_3_3_3_3&s",
                            IsDeleted = false,
                            MaxDistance = 480,
                            Model = "I-PACE SE",
                            Name = "Jaguar I-PACE",
                            PlateNumber = "59O-33456",
                            PricePerDay = 2150000m,
                            PricePerHour = 270000m,
                            StationId = 1,
                            Status = 0,
                            UpdateDate = new DateTime(2025, 10, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VehicleType = "car",
                            seartCapacity = 5
                        },
                        new
                        {
                            Id = 31,
                            BatteryCapacity = 66m,
                            Brand = "Chevrolet",
                            CreateDate = new DateTime(2025, 10, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Features = "{\"gps\":true,\"insurance\":true,\"bluetooth\":true,\"airConditioner\":true,\"backupCamera\":true}",
                            ImageUrl = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ4_4_4_4_4_4_4_4&s",
                            IsDeleted = false,
                            MaxDistance = 417,
                            Model = "Bolt EV",
                            Name = "Chevrolet Bolt EV",
                            PlateNumber = "51O-44567",
                            PricePerDay = 1280000m,
                            PricePerHour = 160000m,
                            StationId = 2,
                            Status = 0,
                            UpdateDate = new DateTime(2025, 10, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VehicleType = "car",
                            seartCapacity = 5
                        },
                        new
                        {
                            Id = 32,
                            BatteryCapacity = 82m,
                            Brand = "Volkswagen",
                            CreateDate = new DateTime(2025, 10, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Features = "{\"gps\":true,\"insurance\":true,\"bluetooth\":true,\"airConditioner\":true,\"spacious\":true,\"familyFriendly\":true}",
                            ImageUrl = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR5_5_5_5_5_5_5_5&s",
                            IsDeleted = false,
                            MaxDistance = 450,
                            Model = "ID.Buzz Pro",
                            Name = "Volkswagen ID.Buzz",
                            PlateNumber = "59P-55678",
                            PricePerDay = 2200000m,
                            PricePerHour = 280000m,
                            StationId = 3,
                            Status = 0,
                            UpdateDate = new DateTime(2025, 10, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VehicleType = "car",
                            seartCapacity = 7
                        },
                        new
                        {
                            Id = 33,
                            BatteryCapacity = 112.5m,
                            Brand = "Lucid",
                            CreateDate = new DateTime(2025, 10, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Features = "{\"gps\":true,\"insurance\":true,\"bluetooth\":true,\"airConditioner\":true,\"leatherSeats\":true,\"luxuryInterior\":true,\"advancedTech\":true}",
                            ImageUrl = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS6_6_6_6_6_6_6_6&s",
                            IsDeleted = false,
                            MaxDistance = 650,
                            Model = "Air Touring",
                            Name = "Lucid Air",
                            PlateNumber = "51P-66789",
                            PricePerDay = 3200000m,
                            PricePerHour = 400000m,
                            StationId = 4,
                            Status = 0,
                            UpdateDate = new DateTime(2025, 10, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VehicleType = "car",
                            seartCapacity = 5
                        },
                        new
                        {
                            Id = 34,
                            BatteryCapacity = 112m,
                            Brand = "Fisker",
                            CreateDate = new DateTime(2025, 10, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Features = "{\"gps\":true,\"insurance\":true,\"bluetooth\":true,\"airConditioner\":true,\"solarPanel\":true,\"sustainableDesign\":true}",
                            ImageUrl = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS7_7_7_7_7_7_7_7&s",
                            IsDeleted = false,
                            MaxDistance = 440,
                            Model = "Ocean Extreme",
                            Name = "Fisker Ocean",
                            PlateNumber = "59Q-77890",
                            PricePerDay = 1600000m,
                            PricePerHour = 200000m,
                            StationId = 1,
                            Status = 0,
                            UpdateDate = new DateTime(2025, 10, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VehicleType = "car",
                            seartCapacity = 5
                        },
                        new
                        {
                            Id = 35,
                            BatteryCapacity = 99m,
                            Brand = "Genesis",
                            CreateDate = new DateTime(2025, 10, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Features = "{\"gps\":true,\"insurance\":true,\"bluetooth\":true,\"airConditioner\":true,\"leatherSeats\":true,\"premiumAudio\":true,\"luxuryBrand\":true}",
                            ImageUrl = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS8_8_8_8_8_8_8_8&s",
                            IsDeleted = false,
                            MaxDistance = 480,
                            Model = "GV70 Electrified",
                            Name = "Genesis GV70",
                            PlateNumber = "51Q-88901",
                            PricePerDay = 2150000m,
                            PricePerHour = 270000m,
                            StationId = 2,
                            Status = 0,
                            UpdateDate = new DateTime(2025, 10, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VehicleType = "car",
                            seartCapacity = 5
                        },
                        new
                        {
                            Id = 36,
                            BatteryCapacity = 71.4m,
                            Brand = "Subaru",
                            CreateDate = new DateTime(2025, 10, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Features = "{\"gps\":true,\"insurance\":true,\"bluetooth\":true,\"airConditioner\":true,\"awd\":true,\"offRoad\":true}",
                            ImageUrl = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS9_9_9_9_9_9_9_9&s",
                            IsDeleted = false,
                            MaxDistance = 460,
                            Model = "Solterra Premium",
                            Name = "Subaru Solterra",
                            PlateNumber = "59R-99012",
                            PricePerDay = 1750000m,
                            PricePerHour = 220000m,
                            StationId = 3,
                            Status = 0,
                            UpdateDate = new DateTime(2025, 10, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VehicleType = "car",
                            seartCapacity = 5
                        },
                        new
                        {
                            Id = 37,
                            BatteryCapacity = 112m,
                            Brand = "Lotus",
                            CreateDate = new DateTime(2025, 10, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Features = "{\"gps\":true,\"insurance\":true,\"bluetooth\":true,\"airConditioner\":true,\"sportDesign\":true,\"performanceMode\":true}",
                            ImageUrl = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS0_0_0_0_0_0_0_0&s",
                            IsDeleted = false,
                            MaxDistance = 520,
                            Model = "Eletre Sport",
                            Name = "Lotus Eletre",
                            PlateNumber = "51R-00123",
                            PricePerDay = 2300000m,
                            PricePerHour = 290000m,
                            StationId = 4,
                            Status = 0,
                            UpdateDate = new DateTime(2025, 10, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VehicleType = "car",
                            seartCapacity = 5
                        },
                        new
                        {
                            Id = 38,
                            BatteryCapacity = 35.5m,
                            Brand = "Mazda",
                            CreateDate = new DateTime(2025, 10, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Features = "{\"gps\":true,\"insurance\":true,\"bluetooth\":true,\"airConditioner\":true,\"stylishDesign\":true}",
                            ImageUrl = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS1_1_1_1_1_1_1_1&s",
                            IsDeleted = false,
                            MaxDistance = 290,
                            Model = "MX-30",
                            Name = "Mazda MX-30",
                            PlateNumber = "59S-11234",
                            PricePerDay = 1360000m,
                            PricePerHour = 170000m,
                            StationId = 1,
                            Status = 0,
                            UpdateDate = new DateTime(2025, 10, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VehicleType = "car",
                            seartCapacity = 5
                        },
                        new
                        {
                            Id = 39,
                            BatteryCapacity = 52m,
                            Brand = "Renault",
                            CreateDate = new DateTime(2025, 10, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Features = "{\"gps\":true,\"insurance\":true,\"bluetooth\":true,\"airConditioner\":true,\"retroDesign\":true,\"sporty\":true}",
                            ImageUrl = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS2_2_2_2_2_2_2_2&s",
                            IsDeleted = false,
                            MaxDistance = 380,
                            Model = "5 Turbo 3E",
                            Name = "Renault 5 Turbo 3E",
                            PlateNumber = "51S-22345",
                            PricePerDay = 1440000m,
                            PricePerHour = 180000m,
                            StationId = 2,
                            Status = 0,
                            UpdateDate = new DateTime(2025, 10, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VehicleType = "car",
                            seartCapacity = 4
                        },
                        new
                        {
                            Id = 40,
                            BatteryCapacity = 42m,
                            Brand = "Fiat",
                            CreateDate = new DateTime(2025, 10, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Features = "{\"gps\":true,\"insurance\":true,\"bluetooth\":true,\"airConditioner\":true,\"compact\":true,\"cityFriendly\":true}",
                            ImageUrl = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS3_3_3_3_3_3_3_3&s",
                            IsDeleted = false,
                            MaxDistance = 330,
                            Model = "500e",
                            Name = "Fiat 500e",
                            PlateNumber = "59T-33456",
                            PricePerDay = 1120000m,
                            PricePerHour = 140000m,
                            StationId = 3,
                            Status = 0,
                            UpdateDate = new DateTime(2025, 10, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VehicleType = "car",
                            seartCapacity = 4
                        },
                        new
                        {
                            Id = 41,
                            BatteryCapacity = 54m,
                            Brand = "MINI",
                            CreateDate = new DateTime(2025, 10, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Features = "{\"gps\":true,\"insurance\":true,\"bluetooth\":true,\"airConditioner\":true,\"compact\":true,\"fun\":true}",
                            ImageUrl = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS4_4_4_4_4_4_4_4&s",
                            IsDeleted = false,
                            MaxDistance = 270,
                            Model = "Cooper SE",
                            Name = "MINI Cooper SE",
                            PlateNumber = "51T-44567",
                            PricePerDay = 1240000m,
                            PricePerHour = 155000m,
                            StationId = 4,
                            Status = 0,
                            UpdateDate = new DateTime(2025, 10, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VehicleType = "car",
                            seartCapacity = 4
                        },
                        new
                        {
                            Id = 42,
                            BatteryCapacity = 77m,
                            Brand = "Opel",
                            CreateDate = new DateTime(2025, 10, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Features = "{\"gps\":true,\"insurance\":true,\"bluetooth\":true,\"airConditioner\":true,\"spacious\":true,\"practical\":true}",
                            ImageUrl = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS5_5_5_5_5_5_5_5&s",
                            IsDeleted = false,
                            MaxDistance = 440,
                            Model = "Grandland Electric",
                            Name = "Opel Grandland",
                            PlateNumber = "59U-55678",
                            PricePerDay = 1600000m,
                            PricePerHour = 200000m,
                            StationId = 1,
                            Status = 0,
                            UpdateDate = new DateTime(2025, 10, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VehicleType = "car",
                            seartCapacity = 5
                        },
                        new
                        {
                            Id = 43,
                            BatteryCapacity = 82m,
                            Brand = "Cupra",
                            CreateDate = new DateTime(2025, 10, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Features = "{\"gps\":true,\"insurance\":true,\"bluetooth\":true,\"airConditioner\":true,\"sportStyle\":true,\"performance\":true}",
                            ImageUrl = "https://encrypted-tbn0.gstatic.com/images?q=tbn:AnD9GcS6_6_6_6_6_6_6_6&s",
                            IsDeleted = false,
                            MaxDistance = 500,
                            Model = "Born e-Boost",
                            Name = "Cupra Born",
                            PlateNumber = "51U-66789",
                            PricePerDay = 1680000m,
                            PricePerHour = 210000m,
                            StationId = 2,
                            Status = 0,
                            UpdateDate = new DateTime(2025, 10, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VehicleType = "car",
                            seartCapacity = 5
                        });
                });

            modelBuilder.Entity("DataAccessLayer.Entities.InspectionProblem", b =>
                {
                    b.HasOne("DataAccessLayer.Entities.RentalRecord", "RentalRecord")
                        .WithMany("InspectionProblems")
                        .HasForeignKey("RentalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("RentalRecord");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.Payment", b =>
                {
                    b.HasOne("DataAccessLayer.Entities.RentalRecord", "RentalRecord")
                        .WithMany("Payments")
                        .HasForeignKey("RentalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("RentalRecord");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.RatingReview", b =>
                {
                    b.HasOne("DataAccessLayer.Entities.RentalRecord", "RentalRecord")
                        .WithOne("RatingReview")
                        .HasForeignKey("DataAccessLayer.Entities.RatingReview", "RentalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("RentalRecord");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.RentalRecord", b =>
                {
                    b.HasOne("DataAccessLayer.Entities.Station", "PickupStation")
                        .WithMany("PickupRentalRecords")
                        .HasForeignKey("PickupStationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DataAccessLayer.Entities.Account", "Renter")
                        .WithMany("RentalRecords")
                        .HasForeignKey("RenterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DataAccessLayer.Entities.Station", "ReturnStation")
                        .WithMany("ReturnRentalRecords")
                        .HasForeignKey("ReturnStationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DataAccessLayer.Entities.Vehicle", "Vehicle")
                        .WithMany("RentalRecords")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PickupStation");

                    b.Navigation("Renter");

                    b.Navigation("ReturnStation");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.Vehicle", b =>
                {
                    b.HasOne("DataAccessLayer.Entities.Station", "Station")
                        .WithMany("Vehicles")
                        .HasForeignKey("StationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Station");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.Account", b =>
                {
                    b.Navigation("RentalRecords");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.RentalRecord", b =>
                {
                    b.Navigation("InspectionProblems");

                    b.Navigation("Payments");

                    b.Navigation("RatingReview")
                        .IsRequired();
                });

            modelBuilder.Entity("DataAccessLayer.Entities.Station", b =>
                {
                    b.Navigation("PickupRentalRecords");

                    b.Navigation("ReturnRentalRecords");

                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.Vehicle", b =>
                {
                    b.Navigation("RentalRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
